ego:
  noise_level: 1.0
  pos_x_std: 0.05
  pos_y_std: 0.05
  yaw_std_deg: 0.2
  velocity_std_kmh: 0.05
  acceleration_std: 0.05

environment:
  noise_level: 1.0
  pos_x_std: 0.3
  pos_y_std: 0.3
  yaw_std_deg: 3.0
  velocity_std_kmh: 1.0
  acceleration_std: 0.8