ego:
  noise_level: 0.0
  pos_x_std: 0.0
  pos_y_std: 0.0
  yaw_std_deg: 0.0
  velocity_std_kmh: 0.0
  acceleration_std: 0.0

environment:
  noise_level: 0.0
  pos_x_std: 0.0
  pos_y_std: 0.0
  yaw_std_deg: 0.0
  velocity_std_kmh: 0.0
  acceleration_std: 0.0