# ---------------------------------------------------------
# Timing & Resolution 
# ---------------------------------------------------------
horizon: 7000             # Planning horizon [ms]
dt_sim: 1000                # Internal integration step via kinematic model [ms]
#dt_interpolation: 100      # Internal interpolation resolution for calculating object distances [ms]
dt_output: 1000            # Output resolution (multiple of dt_sim) [ms]

# ---------------------------------------------------------
# Constraints
# ---------------------------------------------------------
max_compute_time: 5000     # Time budget [ms]
extract_path_time: 5

# ---------------------------------------------------------
# Goal Region
# ---------------------------------------------------------
horizon_increment: 20.0    # Increment on the planning horizon for the Goal Region in percent
goal_region_min_speed: 7.0