# ---------------------------------------------------------
# Timing & Resolution 
# ---------------------------------------------------------
horizon: 7500             # Planning horizon [ms]
dt_sim: 1500    #1000*6            # Internal integration step via kinematic model [ms]
#dt_interpolation: 100      # Internal interpolation resolution for calculating object distances [ms]
dt_output: 1500            # Output resolution (multiple of dt_sim) [ms]

# ---------------------------------------------------------
# Constraints
# ---------------------------------------------------------
max_compute_time: 10000     # Time budget [ms]
extract_path_time: 5

# ---------------------------------------------------------
# Goal Region
# ---------------------------------------------------------
horizon_increment: 20.0    # Increment on the planning horizon for the Goal Region in percent
goal_region_min_speed: 7.0

# ---------------------------------------------------------
# State Pruning Tolerances (Duplicate Detection)
# ---------------------------------------------------------
tolerances:
  pos: 0.5           # Spatial tolerance [m]
  yaw: 0.087         # Heading tolerance [rad] (~5 degrees)
  velocity: 0.5      # Velocity tolerance [m/s]
  acceleration: 0.5  # Acceleration tolerance [m/s^2]
